### ISSUE TITLE
Privileges required for running snowchange

### ISSUE THREAD

**Issue by bidutch** [Snowflake-Labs/snowchange#16]
I am currently getting Snowchange up&running, an observation here: due to the use of the CREATE DATABASE IF NOT EXISTS command, SYSADMIN privileges are required for the user running Snowchange. In our current plan for implementation, we run Snowchange from the commandline, moving towards a docker setup perhaps in the future. Our security setup is that the roles like SYSADMIN/ACCOUNTADMIN/SECURITYADMIN require MFA. Any thoughts on this, one of our options so far is to exclude creation of the database from Snowchange. The change in the code we made for that is instead of the CREATE DATABASE IF NOT EXIST -> USE DATABASE. Am curious how your thoughts on this are

**Comment by qqcvd** [comment]
I'd like to share my thoughs,
When I use snowchange, I use a role that has grants only on the target database (the DEV db or INT db or PROD db....)
(in fact , I use the role that owns the target DB)
that's why 
 - I use the '-c' option to write the log in a local CHANGE_HISTORY table (in the target DB)
 - I commented in the python script the 'CREATE DATABASE' line
I agree with bidutch that the installation role should not have to many rights.

**Comment by sfc-gh-jhansen** [comment]
Thanks for the suggestion @bidutch! Your concerns definitely make sense. One way to approach it would be to have a command line argument that would toggle whether or not snowchange automatically tries to create the CHANGE_HISTORY table (including the containing DB and Schema). So essentially it would be similar to what @qqcvd accomplished by commenting out that line.

What are you thinking? What would make the most sense for you all in practice?

**Comment by bidutch** [comment]
actually I implemented the same as @qqcvd by commenting out this line, just as a workaround. Feature toggle for this sounds like a good approach. Then we indeed can follow our implementation strategy where the scripts are executed under the DB_OWNER rol we create for each database

**Comment by sfc-gh-jhansen** [comment]
Thanks @bidutch and @qqcvd. I do think this would be a good change to make. There are three steps to setup the change history table:

1. CREATE DATABASE IF NOT EXISTS
2. CREATE SCHEMA IF NOT EXISTS
3. CREATE TABLE IF NOT EXISTS

Is it just the first one (the database) that is the major problem? What about the script creating the schema and table, should those be included in the scope of the optional flag? It seems like it depends on how folks setup their security/roles so curious if you think it's OK to still have the script run #2 and #3 in your environments.

Please feel free to make the changes in your fork and submit a PR!

**Comment by sfc-gh-jhansen** [comment]
Just want to follow-up here @bidutch, @qqcvd, and @nugic. Please see my last comment with some clarifying questions. This definitely seems like an issue to address, just want to see what make the most sense (beyond just skipping the CREATE DATABASE step).

**Comment by sfc-gh-jhansen** [comment]
Alright, I went ahead and made changes that I believe make sense. There is now a check at the beginning to see if the metadata table exists. If it does nothing happens, if it doesn't and you've specified the new command line option to create the change history table it creates only the schema and table (not the database), otherwise it throws an error. So the script never creates the metadata database and only creates the schema and table if explicitly selected. Please check out the changes and let me know if they make sense. Happy to tweak them as needed.
