### ISSUE TITLE
version sorting

### ISSUE THREAD

**Issue by qqcvd** [Snowflake-Labs/snowchange#21]
Hi all,
I have the same probleme than in the "Version Sorting and max published version" issue.
You answered that the solution was : 
" I would advise against using two different naming conventions for the version, that can lead to weird problems. You should adopt a standard like two parts or three parts and stick with it."
I understand the point , but it happens that I need to insert a file afterwards, because of a quick patch applied in production for exemple whereas my dev is still in the DEV environment.
Do you think that it is possible to correct the behaviour of the tool?
Regards
SB

**Comment by sfc-gh-jhansen** [comment]
Hey there @qqcvd, the general behavior of imperative style database change management tools like snowchange, is to only apply newer scripts. Since everything is versioned with a unique number you always apply newer versions. Remember that there is no inherent meaning to the version numbers other than the order. So in general I would advice against a system that either tries to give meaning to the version numbers or one that tries to insert version numbers between previous ones (which really goes against the whole idea).

in my experience the best way to handle the situation you're describing is with version control and branching strategies. You would create/use a hotfix branch, add a change script with the next version number, deploy. Then merge that back to your dev branches and rename the scripts in development appropriately.

Hope that makes sense and helps!
