### ISSUE TITLE
component option

### ISSUE THREAD

**Issue by qqcvd** [Snowflake-Labs/snowchange#22]
Hi all,
I'd like to share with you a new use case.
I create the directory structure like that : 
DB_NAME/
    |-- Schema_1/
    |-- Schema_2/
    |-- Schema_3/
Thus , we may be more than one working in parallel on different schemas.
So, to my mind, it would be interesting to have a "component" field in the HISTORY table which would allow to have developpements in parallele , and numbering in parallele.
I know it is possible to have the same feature by using the -c option, but il wil create as much HISTO table as schemas... it seems too much...

**Comment by sfc-gh-jhansen** [comment]
Hey @qqcvd, like a few other issues/ideas you've suggested my experience is that this is best handled through a robust branching strategy in your source control system (presumably git). It's precisely a strategy like that they enables teams to work in parallel on different features. With implicit style database change management tools the challenge is that version numbers have to be unique. I do have a simple feature in snowchange which will cause it to fail if it finds the same version number in your repo. So that way, when a team merges their changes back to a main dev or test branch where the same version # is then it will fail there during integration tests.

Would love to hear any other suggestions for dealing with the inherent version # collisions that happen with this style of tool.

**Comment by qqcvd** [comment]
Hello Jeremiah

I tested Sqitch this week ( I just followed the tutorial :-) )
This tool creates a specific file which contains the dependencies between the "migration" files. Thus, there is not any constraint on the naming of the files and I think you can develop on parallel branches without naming collision issue.

**Comment by sfc-gh-jhansen** [comment]
Glad to hear you found a different approach/tool that works for you. But one word of caution, you can still have the same types of merge conflicts with Sqitch. Since there is a single file that defines the changes and dependencies between them you can run into the same problem (depending on the specific dependencies). But again, most of these types of issues/concerns are generally addressed through a branching/release strategy.
